import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Dashboard from "./components/dashboard";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen bg-neutral-950`}>
        <div className="flex min-h-screen relative">
          <Dashboard />
          <main className="flex-1 overflow-y-auto pl-48">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
